### ISSUE TITLE
 No listeners executed; falling back to catch-all

### ISSUE THREAD

**Issue by willwen** [Microsoft/BotFramework-Hubot#21] opened 2017-09-18 18:55 UTC
Hi,
I am trying to test the adapter out of box. I registered my bot on dev.botframework and sideloaded it through teams.
I run hubot with adapter:
`$ ./bin/hubot -a BotFramework --alias !`
When I go into a channel and type:
@Rosie badger,
I expect a response from example.coffee:
```
robot.hear /badger/i, (res) ->
    res.send "Badgers? BADGERS? WE DON'T NEED NO STINKIN BADGERS"
```

Snippet of just running through shell without adapter `./bin/hubot`:

```
rosie2> rosie2 badger

rosie2 badger

rosie2> [Mon Sep 18 2017 14:48:08 GMT-0400 (Eastern Daylight Time)] DEBUG Message 'rosie2 badger' matched regex //badger/i/; listener.options = { id: null }

[Mon Sep 18 2017 14:48:08 GMT-0400 (Eastern Daylight Time)] DEBUG Executing listener callback for Message 'rosie2 badger'

Badgers?  BADGERS? WE DON'T NEED NO STINKIN BADGERS
```

**However, using MSTeams adapter,  I always get no listeners executed, falling back to catch all:**

```
[Mon Sep 18 2017 14:28:49 GMT-0400 (Eastern Daylight Time)] INFO hubot-botframework-adapter: onBotEvents

[Mon Sep 18 2017 14:28:49 GMT-0400 (Eastern Daylight Time)] INFO hubot-botframework-adapter: Handling activity Channel: msteams; type: message

[Mon Sep 18 2017 14:28:49 GMT-0400 (Eastern Daylight Time)] INFO hubot-botframework-middleware: creating middleware...

[Mon Sep 18 2017 14:28:49 GMT-0400 (Eastern Daylight Time)] INFO hubot-msteams: toReceivable

[Mon Sep 18 2017 14:28:49 GMT-0400 (Eastern Daylight Time)] INFO hubot-botframework-adapter: 
{
	"user": {
		"id": "2xxA",
		"name": "Will W",
		"tenant": "efc88xxxx3f835af",
		"activity": {
			"text": "rosie2  badger",
			"textFormat": "plain",
			"attachments": [
				{
					"contentType": "text/html",
					"content": "<div><span itemscope=\"\" itemtype=\"http://schema.skype.com/Mention\" itemid=\"0\">Rosie</span>&nbsp;badger</div>"
				}
			],
			"type": "message",
			"timestamp": "2017-09-18T18:28:36.619Z",
			"localTimestamp": "2017-09-18T14:28:36.619-04:00",
			"entities": [
				{
					"mentioned": {
						"id": "28:7db26xxxxxxx7ef3e9",
						"name": "Rosie"
					},
					"text": "<at>Rosie</at>",
					"type": "mention"
				},
				{
					"locale": "en-US",
					"country": "US",
					"platform": "Windows",
					"type": "clientInfo"
				}
			],
			"sourceEvent": {
				"teamsChannelId": "19:xxxxxxxxxx@thread.skype",
				"teamsTeamId": "19:xxxxxxxxxxxx@thread.skype",
				"channel": {
					"id": "19:638607xxxxxxxxx469ba@thread.skype"
				},
				"team": {
					"id": "19:6386079xxxxxxxxx469ba@thread.skype"
				},
				"tenant": {
					"id": "efc8xxxxxxca3f835af"
				}
			},
			"address": {
				"id": "150xxxxx6511",
				"channelId": "msteams",
				"user": {
					"id": "29:1F9J5Oxxxxxxxxxxxxxxxxe476TUrYl9vgA",
					"name": "Will"
				},
				"conversation": {
					"isGroup": true,
					"id": "19:638xxxxxxxxxxx469ba@thread.skype;messageid=150xxxx6511"
				},
				"bot": {
					"id": "28:7db26cxxxxxxxxxxxxef3e9",
					"name": " rosie2"
				},
				"serviceUrl": "https://smba.trafficmanager.net/amer-client-ss.msg/"
			},
			"source": "msteams"
		},
		"room": "19:63860xxxxxxxxxxxxx6469ba@thread.skype;messageid=1505xxxxxx6511"
	},
	"text": "rosie2  badger",
	"id": "150xxxx16511",
	"done": false,
	"room": "19:6386079a42xxxxxxxba@thread.skype;messageid=1505xxxxxxx11"
}

[Mon Sep 18 2017 14:28:49 GMT-0400 (Eastern Daylight Time)] DEBUG No listeners executed; falling back to catch-all
```
Does it have to do with the text field having two spaces between 'rosie2' and 'badger'
"text": "rosie2  badger"
The mention is to Rosie, but the text has rosie2 badger.

**Comment by willwen** [comment] 2017-09-26 15:08
I guess no one else has this problem :(

**Comment by MattSFT** [comment] 2017-09-26 15:11
Hey Will. Sorry this issue slipped my mind. I'll take a look at it today. Are you by any chance copying and pasting the message into teams or typing it out directly?

**Comment by willwen** [comment] 2017-09-26 15:12
Hi Matt, thanks for getting back, I am typing it out directly every time

**Comment by MattSFT** [comment] 2017-09-26 15:17
The rosie2 part is because the adapter replaces the mentioned bot name in teams with the hubot name the all of the regexes have been registered with. Let me try to reproduce the issue locally and see if I can get a fix out.

**Comment by willwen** [comment] 2017-09-26 15:22
okay, thanks a bunch, if you have trouble reproducing the bug, then just confirm with me that you have no problems, and i'll register another bot from scratch. 
I am assuming since the adapter does a name replace, the BotFramework name DOES NOT have to match the local hubot name

**Comment by MattSFT** [comment] 2017-09-26 20:14
You are correct in that the bot framework name does not need to match. Looking at your issue now.

**Comment by MattSFT** [comment] 2017-09-26 20:39
This seems to be working for me.

![inteam](https://user-images.githubusercontent.com/29067893/30883121-0b5a3c3a-a2c0-11e7-958c-f1ff308592af.PNG)

**Comment by MattSFT** [comment] 2017-09-26 20:43
I set up the bot using yo hubot and chose botframework as the adapter.

Then I updated the example.coffee script to uncomment the badger script.

Here is a zip of my bot: [HubotBot.zip](https://github.com/Microsoft/BotFramework-Hubot/files/1334921/HubotBot.zip)

**Comment by willwen** [comment] 2017-09-26 20:44
Okay, I guess I messed up somewhere, and I'll start again tomorrow. I'll update on my progress then.

**Comment by MattSFT** [comment] 2017-09-26 20:46
make sure you're running the latest hubot-botframework package

**Comment by willwen** [comment] 2017-09-26 21:53
Ok, it works for me now too:
![1](https://user-images.githubusercontent.com/9434028/30885559-b9c689f6-a2e1-11e7-80b7-877df5e7e508.PNG)

Somethings that I noticed that I did differently was:
1)
```
    "hubot-botframework": "^0.10.0",
vs 
    "hubot-botframework": "^0.10.1",
```
and 
2)
**I also used npm link rather than static files in node_modules/**

![2](https://user-images.githubusercontent.com/9434028/30885968-54394716-a2e3-11e7-8165-8f47a900c598.PNG)
In the above image you can see my version, the symbolic link (8/29/2017) vs your new version (9/26/2017) 

See if you have the same error if you use a symbolic link as per described: 
https://hubot.github.com/docs/adapters/development/

**Comment by MattSFT** [comment] 2017-09-26 23:32
The version might actually do the trick. There were quite a few large changes in the teams code between v 0.10.0 and 0.10.1

**Comment by MattSFT** [comment] 2017-09-27 00:10
Oh I see. You probably grabbed the code because we hadn't published the latest version. you should be okay with just grabbing the npm package instead of pulling the code and doing a symbolic link. Not sure of any reason why you would want the symbolic link.

**Comment by MattSFT** [comment] 2017-09-27 00:15
I'm going to go ahead and close this issue since it is working for you now.

**Closed by MattSFT** 2017-09-27 00:15 UTC
